version: '3'
services:
  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: "no"

  inventory-management:
    image: inventory-managemnet
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-managemnet
    ports:
     - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: "no"
